[package]
name = "music_library_manager"
version = "0.1.0"
edition = "2021"
description = "A CLI for handling Simon Goričar's music library."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
toml = "0.5.9"
owo-colors = "3.4.0"
lazy_static = "1.4.0"
regex = "1.5.6"
unicode-segmentation = "1.9.0"
pathdiff = "0.2.1"
indicatif = "0.17.0-rc.11"
