[package]
name = "euphony"
version = "0.1.0"
edition = "2021"
description = "A personal and opinionated music library manager."
readme = "README.md"
authors = ["Simon Goričar <simon.peter.goricar@gmail.com>"]
repository = "https://github.com/DefaultSimon/euphony"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive", "wrap_help"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
toml = "0.5.9"
lazy_static = "1.4.0"
pathdiff = "0.2.1"
indicatif = "0.17.0-rc.11"
console = "0.15.0"
dialoguer = "0.10.1"
