[package]
name = "music_library_manager"
version = "0.1.0"
edition = "2021"
description = "A CLI for handling Simon Goričar's music library."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.9"
