[package]
name = "euphony"
version = "1.1.0"
edition = "2021"
description = "A personal and opinionated music library transcode manager."
readme = "README.md"
authors = ["Simon Goričar <simon.peter.goricar@gmail.com>"]
repository = "https://github.com/DefaultSimon/euphony"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
toml = "0.5.9"
lazy_static = "1.4.0"
pathdiff = "0.2.1"
dunce = "1.0.2"
rayon = "1.5.3"
state = "0.5.3"
miette = "5.4.1"
tui = "0.19.0"
crossterm = "0.25.0"
rand = "0.8.5"
