[package]
name = "euphony"
version = "1.2.0"
edition = "2021"
description = "A personal and opinionated music library transcode manager."
readme = "README.md"
authors = ["Simon Goričar <simon.peter.goricar@gmail.com>"]
repository = "https://github.com/DefaultSimon/euphony"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
toml = "0.5.9"
pathdiff = "0.2.1"
dunce = "1.0.2"
state = "0.5.3"
miette = { version = "5.5.0", features = ["fancy"]}
tui = "0.19.0"
crossterm = "0.25.0"
rand = "0.8.5"
ansi-to-tui = "2.0.0"
ctrlc = "3.2.3"
crossbeam = "0.8.2"
strip-ansi-escapes = "0.1.1"
