name: Build and test Rust code

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Set up required tools
      run: sudo apt-get update && sudo apt-get install curl build-essential -y
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: Install stable Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Install nextest
      uses: taiki-e/install-action@v2
      with:
        tool: nextest
    - name: Cache
      uses: Swatinem/rust-cache@v2
    - name: Compile project
      run: cargo build --verbose
    - name: Run unit and integration tests
      run: cargo nextest run --all-features --all-targets --workspace --verbose
    - name: Run documentation tests
      run: cargo test --all-features --doc --verbose
